project:
  type: upfthesis
  output-dir: "_thesis"

title: My thesis at Universitat Pompeu Fabra
subtitle: A Quarto extension and template
author: Gonzalo Garcia-Castro
department: Department of Templates
supervisor: Dr. Awesome Thesis
date: "2023"
date-format: "YYYY"
chapters:
  - index.qmd
  - "00_dedication.qmd"
  - "01_acknowledgements.qmd"
  - "02_abstract.qmd"
  - "03_preface.qmd"
  - "04_introduction.qmd"
  - "05_chapter-1.qmd"
  - "06_chapter-2.qmd"
  - "07_discussion.qmd"
  - "08_references.qmd"
output-file: "thesis"

format:
  upfthesis-pdf: default
  upfthesis-docx: default
