project:
  type: upfthesis
  output-dir: "_thesis"

book:
  title: My thesis at Universitat Pompeu Fabra
  subtitle: A Quarto extension and template
  author: Gonzalo Garcia-Castro
  date: "2023"
  date-format: "YYYY"
  chapters:
    - index.qmd
    - chapters/00-dedication.qmd
    - chapters/01-acknowledgements.qmd
    - chapters/02-abstract.qmd
    - chapters/03-preface.qmd
    - chapters/04-introduction.qmd
    - chapters/05-chapter-1.qmd
    - chapters/06-chapter-2.qmd
    - chapters/07-discussion.qmd
    - chapters/08-references.qmd
  output-file: thesis

thesis:
  department: Department of Templates
  supervisor: Dr. Awesome Supervisor

format:
  upfthesis-pdf: default
  upfthesis-docx: default

fig-dpi: 500
fig-align: center
crossref: 
  fig-title: Fig     # (default is "Figure")
  tbl-title: Tab.
lang: en

references: references.bib