project:
  type: upfthesis
  output-dir: "_thesis"

book:
  date-format: "YYYY"
  chapters:
    - index.qmd
    - chapters/01-introduction.qmd
    - chapters/02-chapter-1.qmd
    - chapters/03-chapter-2.qmd
    - chapters/04-discussion.qmd
    - chapters/05-bibliography.qmd
    - chapters/06-glossary.qmd # not required
  output-file: thesis

thesis:
  title: The title of my thesis 
  subtitle: A subtitle
  author: Gonzalo García-Castro
  date: 2023
  department: Department of Templates
  supervisor: Dr. Awesome Supervisor
  dedication: | # not required
    To many people.
  acknowledgements: | # not required
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas auctor quis quam non feugiat. Fusce a eleifend sapien. Fusce vel ipsum vitae purus molestie venenatis in in nunc. Fusce blandit placerat ullamcorper. Aliquam erat volutpat. Integer sed ante porttitor, egestas neque at, molestie neque. In id ante ultricies leo molestie tristique id a tortor. Vivamus ullamcorper, lectus vitae tristique accumsan, nunc nulla cursus urna, in ultricies eros odio nec arcu. Etiam non convallis nulla. Nunc imperdiet nibh at scelerisque interdum. Vivamus mattis placerat justo, nec maximus ligula rutrum et. Sed ut rhoncus dui, ut dignissim justo. Donec vitae sapien tempus, dictum libero sit amet, tincidunt leo. Maecenas auctor libero pellentesque finibus porta.
    Curabitur pretium augue odio, a porttitor purus pellentesque vitae. Maecenas lobortis justo ut eleifend blandit. Morbi nulla dolor, imperdiet eget lacus non, accumsan bibendum turpis. Aenean nec viverra est. Duis laoreet nulla ut diam mattis, vitae pellentesque nibh fringilla. Morbi pellentesque, ante a faucibus auctor, diam augue vehicula dui, auctor interdum sem augue at risus. In hac habitasse platea dictumst. Nam sit amet consectetur lacus, eget gravida orci. Fusce suscipit varius dapibus. Aenean enim mi, vestibulum vitae mi maximus, molestie efficitur odio. Duis aliquam blandit sagittis. Nulla ut volutpat erat.
    Curabitur id ligula dolor. Ut convallis augue mi, sed rutrum urna facilisis eu. Nullam mollis tortor eget massa eleifend pellentesque. Etiam placerat faucibus placerat. Sed et auctor ligula. Pellentesque at dictum ante. Etiam et tempus augue. Sed id elit nibh. Aliquam erat volutpat. Sed vel sem elit.
  abstract-english: |
    Nam non neque aliquet, rutrum tortor eget, pulvinar libero. Integer sed ante nisi. Integer scelerisque interdum nunc, a dictum est vestibulum ac. Aliquam lorem nibh, blandit non ullamcorper sed, fringilla ac enim. Aliquam semper quis tortor sit amet elementum. Praesent orci lectus, rhoncus rutrum nisl ac, aliquet pharetra est. Fusce posuere, risus at ultrices molestie, metus ante dictum augue, eget pulvinar sem justo vitae libero. Nam ut lacus ac nisl dictum cursus. Nullam non justo in ligula lobortis consectetur. Sed pretium mollis quam, sit amet aliquam lorem maximus eget. Cras malesuada efficitur risus id placerat. Nullam et feugiat sapien. In dignissim ante ac nibh varius, eu tincidunt ex molestie. Sed vitae dignissim urna. Donec ac sapien mattis, ultricies eros ut, vehicula mauris.
  abstract-catalan: |
    Nam non neque aliquet, rutrum tortor eget, pulvinar libero. Integer sed ante nisi. Integer scelerisque interdum nunc, a dictum est vestibulum ac. Aliquam lorem nibh, blandit non ullamcorper sed, fringilla ac enim. Aliquam semper quis tortor sit amet elementum. Praesent orci lectus, rhoncus rutrum nisl ac, aliquet pharetra est. Fusce posuere, risus at ultrices molestie, metus ante dictum augue, eget pulvinar sem justo vitae libero. Nam ut lacus ac nisl dictum cursus. Nullam non justo in ligula lobortis consectetur. Sed pretium mollis quam, sit amet aliquam lorem maximus eget. Cras malesuada efficitur risus id placerat. Nullam et feugiat sapien. In dignissim ante ac nibh varius, eu tincidunt ex molestie. Sed vitae dignissim urna. Donec ac sapien mattis, ultricies eros ut, vehicula mauris.
  preface: |
    Mauris facilisis sed purus ornare scelerisque. Sed nulla est, elementum ut lacus et, varius ultrices tellus. Suspendisse fringilla rhoncus pulvinar. Fusce vitae bibendum sapien. Phasellus id nunc eget nulla sodales dignissim id ac arcu. Fusce massa dui, blandit sed malesuada nec, blandit non libero. Morbi sem ligula, pulvinar sit amet nisl id, efficitur consectetur tellus. Sed porta dui nec ligula rutrum laoreet. Suspendisse vitae efficitur risus. Pellentesque gravida nec eros sit amet luctus. Cras ut convallis risus. Sed varius turpis ultricies congue consequat. Aenean pharetra, nibh ac interdum suscipit, lorem turpis cursus mauris, nec molestie nulla diam ac elit.
    Vivamus tempus luctus odio, quis scelerisque purus iaculis sed. Etiam quam diam, euismod ut odio eget, ultricies pharetra massa. Maecenas posuere arcu eu ipsum gravida interdum. Aenean eleifend dolor nec consequat vehicula. In lobortis aliquet gravida. Quisque in risus vestibulum, dignissim tortor et, malesuada lectus. Donec efficitur purus eu tincidunt mattis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed pellentesque gravida placerat. Praesent scelerisque auctor mauris, non pretium urna venenatis vel. Etiam a dui ornare, suscipit erat ut, molestie ante.
    Maecenas ullamcorper risus vitae faucibus tempus. Praesent aliquet quam ac venenatis elementum. Nam posuere justo eget eros condimentum dictum. Duis commodo aliquam eros, nec iaculis enim porta id. In rhoncus, sem eu dictum euismod, enim urna interdum urna, nec porttitor magna lacus in massa. Proin sagittis nisl a nisi feugiat, non lacinia turpis tempus. Morbi non eros venenatis, gravida dolor eu, ultrices nisl. Integer in gravida lorem. Praesent ut nibh felis. Integer sed augue lobortis, vestibulum nisl sed, scelerisque felis. Quisque vehicula turpis metus, quis aliquam ante elementum vitae.

format:
  upfthesis-pdf:
    page-crop: frame # cam, crop, frame
    page-info: noinfo # info, noinfo
    lot: true # show list of tables? (not required)
    lof: true # show list of figures? (not required)
    linestretch: 1.5 # can be 1 or 1.5
  upfthesis-docx: default

fig-dpi: 800
ig-align: center
lang: en

echo: false
warning: false
message: false

csl: apa.csl
bibliography:
  - references.bib