project:
  type: upfthesis
  output-dir: "_thesis"

book:
  title: My thesis at Universitat Pompeu Fabra
  subtitle: A Quarto extension and template
  author: Gonzalo Garcia-Castro
  date: "2023"
  date-format: "YYYY"
  chapters:
    - index.qmd
    - 00-dedication.qmd
    - 01-acknowledgements.qmd
    - 02-abstract.qmd
    - 03-preface.qmd
    - 04-introduction.qmd
    - 05-chapter-1.qmd
    - 06-chapter-2.qmd
    - 07-discussion.qmd
    - 08-references.qmd
  output-file: thesis

thesis:
  department: Department of Templates
  supervisor: Dr. Awesome Supervisor

format:
  upfthesis-pdf: default
  upfthesis-docx: default
